<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.8" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="10.1.7" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Core\Store.Domain\Store.Domain.csproj" />
    <ProjectReference Include="..\..\Core\Store.Service\Store.Service.csproj" />
    <ProjectReference Include="..\..\Infrastructure\Store.Persistent\Store.Persistent.csproj" />
  </ItemGroup>

</Project>
